### ISSUE TITLE
Prettier error

### ISSUE THREAD

**Issue by TakCastel** [nuxt/create-nuxt-app#101] opened 2018-09-27 14:58 UTC
### Version

[v2.0.0](https://github.com/create-nuxt-app/releases/tag/v2.0.0)

### Reproduction link

[https://github.com/Vocast-fr/website](https://github.com/Vocast-fr/website)

### Steps to reproduce

Type the followin command line : 

`$ npx create-nuxt-app test`

Enter the following options : 

```
> Generating Nuxt.js project in <path>
? Project name <projectname>
? Project description My striking Nuxt.js project
? Use a custom server framework none
? Use a custom UI framework vuetify
? Choose rendering mode Single Page App
? Use axios module yes
? Use eslint yes
? Use prettier yes
? Author name
? Choose a package manager npm
```

Then run 

`$ cd <projectname>`

`$ npm run dev`

You will get the following messages :

![Capture d’écran 2018-09-27 à 16.50.15.png](https://cmty.s3.eu-west-1.amazonaws.com/99351826/78c91690-c265-11e8-aa34-f91f7e722ca5.png)

Am I doing something wrong ?

### What is expected ?

The application is launched locally.

### What is actually happening?

Fail to compile with Prettier error.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/create-nuxt-app/issues/c67">#c67</a>)</em></sub></div>

**Comment by aldarund** [comment] 2018-09-27 15:20
@TakCastel it was fixed, but not released. For now you could just lint --fix

**Comment by manniL** [comment] 2018-10-13 00:11
Fixed with https://github.com/nuxt/create-nuxt-app/commit/5ecab1c10aa3bd4933d048b85d161431171eae23

**Comment by skozzii** [comment] 2019-01-05 21:40
This issue has resurfaced.

**Comment by manniL** [comment] 2019-01-05 21:49
@skozzii could you try to send in a fix?

**Comment by nzee** [comment] 2019-03-22 11:43
Fix for this anytime soon?
cc : @aldarund

**Comment by nzee** [comment] 2019-03-23 09:29
Can you brief us on what's the cause for this error so that we can look into pushing a fix?

**Comment by manniL** [comment] 2019-03-23 10:14
@nzee My guess is that there are some eslint-rules that intefere with prettier. you'd have to explicitly disable them when choosing *both* options.

**Comment by aldarund** [comment] 2019-03-23 11:45
@manniL that should be handled by prettier eslint config, that disable conflicting rules
@nzee do u have a reproduction?

**Comment by nzee** [comment] 2019-03-23 12:07
Steps to Reproduce:
`npx create-nuxt-app nuxty`

```
? Project name nuxty
? Project description My impeccable Nuxt.js project
? Use a custom server framework none
? Choose features to install Progressive Web App (PWA) Support, Linter / Formatter, 
Prettier, Axios
? Use a custom UI framework none
? Use a custom test framework none
? Choose rendering mode Universal
? Author name Nazim Zeeshan
? Choose a package manager npm
```

Make any change on index.vue such as indenting wrongly

`npm run dev`

You get the following error
![eslint-error](https://user-images.githubusercontent.com/421439/54865828-aa0baf80-4d91-11e9-8c14-0004970e0907.png)

**.eslintrc.js**
```
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  parserOptions: {
    parser: 'babel-eslint'
  },
  extends: [
    '@nuxtjs',
    'plugin:nuxt/recommended',
    'plugin:prettier/recommended',
    'prettier',
    'prettier/vue'
  ],
  plugins: [
    'prettier'
  ],
  // add your custom rules here
  rules: {
  }
}
```

**.editorconfig**
```
# editorconfig.org
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false
```

**.prettierrc**
```
{
  "semi": false,
  "singleQuote": true
}
```

**package.json**
```
{
  "name": "nuxty",
  "version": "1.0.0",
  "description": "My impeccable Nuxt.js project",
  "author": "Nazim Zeeshan",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "cross-env": "^5.2.0",
    "nuxt": "^2.4.0",
    "@nuxtjs/axios": "^5.3.6",
    "@nuxtjs/pwa": "^2.6.0"
  },
  "devDependencies": {
    "nodemon": "^1.18.9",
    "@nuxtjs/eslint-config": "^0.0.1",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.15.1",
    "eslint-config-standard": ">=12.0.0",
    "eslint-plugin-import": ">=2.16.0",
    "eslint-plugin-jest": ">=22.3.0",
    "eslint-plugin-node": ">=8.0.1",
    "eslint-plugin-nuxt": ">=0.4.2",
    "eslint-plugin-promise": ">=4.0.1",
    "eslint-plugin-standard": ">=4.0.0",
    "eslint-loader": "^2.1.2",
    "eslint-plugin-vue": "^5.2.2",
    "eslint-config-prettier": "^4.1.0",
    "eslint-plugin-prettier": "^3.0.1",
    "prettier": "^1.16.4"
  }
}
```

**Comment by aldarund** [comment] 2019-03-23 12:10
>Make any change on index.vue such as indenting wrongly

So its totally expected if u format code wrong it will error. So you need to fix your code formatting according to how prettier wants.  
It can be done either manually or via eslint --fix or you can configure automatic formatting in your IDE

**Closed** 2019-03-25 18:20 UTC
Labels: cmty:bug-report

**Comment by tr1s** [comment] 2020-03-31 16:24
I'm having similar issues.. at a very specific point the code hits the printWdith dead on, it will try to format and then go back to normal. Never resolving the error. :/
