### ISSUE TITLE
Unknown browser query error

### ISSUE THREAD

**Issue by olivbau** [nuxt/create-nuxt-app#262] opened 2019-06-18 07:59 UTC
Just after a fresh install:
```
npx create-nuxt-app my-app
cd my-app
npm run dev
```
I have the following error: **ERROR  Unknown browser query android all. Maybe you are using old Browserslist or made typo in query.**

```
> nuxt


   ╭─────────────────────────────────────────────╮
   │                                             │
   │   Nuxt.js v2.8.1                            │
   │   Running in development mode (universal)   │
   │                                             │
   │   Listening on: http://localhost:3000/      │
   │                                             │
   ╰─────────────────────────────────────────────╯

ℹ Preparing project for development                                                                        09:42:59
ℹ Initial build may take a while                                                                           09:42:59
✔ Builder initialized                                                                                      09:42:59
✔ Nuxt files generated                                                                                     09:42:59

 ERROR  Unknown browser query android all. Maybe you are using old Browserslist or made typo in query.     09:43:00

  at unknownQuery (node_modules/browserslist/index.js:204:10)
  at node_modules/browserslist/index.js:296:11
  at Array.reduce (<anonymous>)
  at resolve (node_modules/browserslist/index.js:237:18)
  at browserslist (node_modules/browserslist/index.js:361:16)
  at supportedBrowsers.some.supportedBrowser (node_modules/postcss-preset-env/index.js:438:105)
  at Array.some (<anonymous>)
  at stagedFeatures.filter.feature (node_modules/postcss-preset-env/index.js:438:80)
  at Array.filter (<anonymous>)
  at postcss$1.plugin.opts (node_modules/postcss-preset-env/index.js:438:44)
  at creator (node_modules/postcss/lib/postcss.js:133:35)
  at config.plugins.sortPlugins.map (node_modules/@nuxt/webpack/dist/webpack.js:4128:18)
  at Array.map (<anonymous>)
  at PostcssConfig.loadPlugins (node_modules/@nuxt/webpack/dist/webpack.js:4122:10)
  at PostcssConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:4158:14)
  at StyleLoader.postcss (node_modules/@nuxt/webpack/dist/webpack.js:4215:39)
```

**Comment by TonSDe** [comment] 2019-06-18 08:01
I have same issue.

**Comment by Xin-X** [comment] 2019-06-18 09:36
I have same issue.
Is there a solution?

**Comment by swearwalker** [comment] 2019-06-18 10:48
@Xin-X https://twitter.com/Browserslist/status/1140911400304467968. check this twit

**Comment by tatump** [comment] 2019-06-18 10:49
temporary solution
npm i browserslist --save

or edit package.json
"browserslist": [],

This works!
https://github.com/facebook/create-react-app/issues/7239

**Comment by lenvonsam** [comment] 2019-06-19 00:59
i have the same issue.
Any solution?

**Comment by clarkdo** [comment] 2019-06-24 08:43
This is an issue from caniuse-lite, it's duplicate of https://github.com/nuxt/create-nuxt-app/issues/262, let's trace in that ticket.

**Closed by clarkdo** 2019-06-24 08:43 UTC
