### ISSUE TITLE
Unable to setup project.

### ISSUE THREAD

**Issue by mirajnetxp** [nuxt/create-nuxt-app#104] opened 2018-10-01 05:16 UTC
Getting this error every time.

Unexpected end of JSON input while parsing near '...DRuXj+pSHLyPa\nS0l5eK'

My npm vertion is     5.6.0

**Comment by ejlocop** [comment] 2018-10-03 12:15
same with me 
```
npm ERR! Unexpected end of JSON input while parsing near '...b89f35a76","tarball":'
```

this is my log file

> 783 silly resolveWithNewModule @nuxtjs/axios@5.3.3 checking installable status
> 784 http fetch GET 200 https://registry.npmjs.org/nuxt 9ms (from cache)
> 785 silly pacote range manifest for cross-env@^5.1.6 fetched in 11ms
> 786 silly resolveWithNewModule cross-env@5.2.0 checking installable status
> 787 silly fetchPackageMetaData error for nuxt@^2.0.0 Unexpected end of JSON input while parsing near '...b89f35a76","tarball":'
> 788 http fetch GET 200 https://registry.npmjs.org/express 12ms (from cache)
> 789 silly fetchPackageMetaData error for express@^4.16.3 Unexpected end of JSON input while parsing near '..."dependencies":{"conn'
> 790 silly saveTree Taraveler@1.0.0
> 790 silly saveTree +-- @nuxtjs/axios@5.3.3
> 790 silly saveTree `-- cross-env@5.2.0
> 791 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...b89f35a76","tarball":'
> 791 verbose stack     at JSON.parse (<anonymous>)
> 791 verbose stack     at parseJson (C:\Users\tealiedie\AppData\Roaming\nvm\v8.10.0\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-better-errors\index.js:7:17)
> 791 verbose stack     at consumeBody.call.then.buffer (C:\Users\tealiedie\AppData\Roaming\nvm\v8.10.0\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50)
> 791 verbose stack     at <anonymous>
> 791 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
> 792 verbose cwd D:\Projects\taraveler-mevn
> 793 verbose Windows_NT 10.0.14393
> 794 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
> 795 verbose node v8.10.0
> 796 verbose npm  v5.6.0
> 797 error Unexpected end of JSON input while parsing near '...b89f35a76","tarball":'
> 798 verbose exit [ 1, true ]

**Comment by aldarund** [comment] 2018-10-03 12:17
When this happens? At what stage? What options did u choose? How create it via yarn or npx?

**Comment by ejlocop** [comment] 2018-10-03 12:19
same error as mine. 
my npm version is: 5.6.0

project created via `npx create-nuxt-app`

```
npm ERR! Unexpected end of JSON input while parsing near '...b89f35a76","tarball":'
```

this is my log file

> 783 silly resolveWithNewModule @nuxtjs/axios@5.3.3 checking installable status
> 784 http fetch GET 200 https://registry.npmjs.org/nuxt 9ms (from cache)
> 785 silly pacote range manifest for cross-env@^5.1.6 fetched in 11ms
> 786 silly resolveWithNewModule cross-env@5.2.0 checking installable status
> 787 silly fetchPackageMetaData error for nuxt@^2.0.0 Unexpected end of JSON input while parsing near '...b89f35a76","tarball":'
> 788 http fetch GET 200 https://registry.npmjs.org/express 12ms (from cache)
> 789 silly fetchPackageMetaData error for express@^4.16.3 Unexpected end of JSON input while parsing near '..."dependencies":{"conn'
> 790 silly saveTree Project@1.0.0
> 790 silly saveTree +-- @nuxtjs/axios@5.3.3
> 790 silly saveTree `-- cross-env@5.2.0
> 791 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...b89f35a76","tarball":'
> 791 verbose stack     at JSON.parse (<anonymous>)
> 791 verbose stack     at parseJson (C:\Users\tealiedie\AppData\Roaming\nvm\v8.10.0\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-better-errors\index.js:7:17)
> 791 verbose stack     at consumeBody.call.then.buffer (C:\Users\tealiedie\AppData\Roaming\nvm\v8.10.0\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50)
> 791 verbose stack     at <anonymous>
> 791 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
> 792 verbose cwd D:\Projects\project
> 793 verbose Windows_NT 10.0.14393
> 794 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
> 795 verbose node v8.10.0
> 796 verbose npm  v5.6.0
> 797 error Unexpected end of JSON input while parsing near '...b89f35a76","tarball":'
> 798 verbose exit [ 1, true ]

**Comment by aldarund** [comment] 2018-10-03 12:21
@ejlocop it fails straight away after npx create-nuxt-app or it ask for options before crash?

**Comment by ejlocop** [comment] 2018-10-03 12:21
same error as mine. 
my npm version is: 5.6.0

project created via `npx create-nuxt-app`
options selected: 
```
- express
- tailwind
- Universal
- axios (yes)
- eslint (yes)
- prettier (yes)
```

```
npm ERR! Unexpected end of JSON input while parsing near '...b89f35a76","tarball":'
```

this is my log file

> 783 silly resolveWithNewModule @nuxtjs/axios@5.3.3 checking installable status
> 784 http fetch GET 200 https://registry.npmjs.org/nuxt 9ms (from cache)
> 785 silly pacote range manifest for cross-env@^5.1.6 fetched in 11ms
> 786 silly resolveWithNewModule cross-env@5.2.0 checking installable status
> 787 silly fetchPackageMetaData error for nuxt@^2.0.0 Unexpected end of JSON input while parsing near '...b89f35a76","tarball":'
> 788 http fetch GET 200 https://registry.npmjs.org/express 12ms (from cache)
> 789 silly fetchPackageMetaData error for express@^4.16.3 Unexpected end of JSON input while parsing near '..."dependencies":{"conn'
> 790 silly saveTree Project@1.0.0
> 790 silly saveTree +-- @nuxtjs/axios@5.3.3
> 790 silly saveTree `-- cross-env@5.2.0
> 791 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...b89f35a76","tarball":'
> 791 verbose stack     at JSON.parse (<anonymous>)
> 791 verbose stack     at parseJson (C:\Users\user\AppData\Roaming\nvm\v8.10.0\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-better-errors\index.js:7:17)
> 791 verbose stack     at consumeBody.call.then.buffer (C:\Users\user\AppData\Roaming\nvm\v8.10.0\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50)
> 791 verbose stack     at <anonymous>
> 791 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
> 792 verbose cwd D:\Projects\project
> 793 verbose Windows_NT 10.0.14393
> 794 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
> 795 verbose node v8.10.0
> 796 verbose npm  v5.6.0
> 797 error Unexpected end of JSON input while parsing near '...b89f35a76","tarball":'
> 798 verbose exit [ 1, true ]

**Comment by aldarund** [comment] 2018-10-03 12:31
@ejlocop cant reproduce . Something wrong with your npm/node. Try npm cache clear --force 
And try to use yarn as a last step

**Comment by aldarund** [comment] 2018-10-03 23:50
@ejlocop did it worked?

**Comment by aldarund** [comment] 2018-10-04 12:18
So it something wrong with node/npm installation.  Nothing to be fixed on create-nuxt-app side

**Closed by aldarund** 2018-10-04 12:18 UTC
