### ISSUE TITLE
install with npx create-nuxt-app, always install old version (v2.3.4)

### ISSUE THREAD

**Issue by willi-dev** [nuxt/create-nuxt-app#296] opened 2019-07-24 09:40 UTC
any suggestion, i install via npx create-nuxt-app, but always v2.3.4 that installed.. 
how to force install to latest version? 

Thanks.

**Comment by clarkdo** [comment] 2019-07-26 12:34
Per npm doc: By default, npx will check whether <command> exists in $PATH, or in the local project binaries, and execute that. If <command> is not found, it will be installed prior to execution.

So you can check 2.3.4 has been installed in your local and uninstall it.

**Comment by manniL** [comment] 2019-07-26 14:53
Duplicate of #209

**Closed by manniL** 2019-07-26 14:53 UTC
