### ISSUE TITLE
Why was Express and other server templates removed from create-nuxt-app?

### ISSUE THREAD

**Issue by robbylucia** [nuxt/create-nuxt-app#569] opened 2020-07-08 17:21 UTC
It was removed, and I don't see a solution being offered that is as easy and fast as the one-click installation from before.
I'd rather use an older version of create-nuxt-app at this point.

Can someone explain why it was removed, and are there plans to make it as easy and fast as it was before?

**Comment by robbylucia** [comment] 2020-07-09 16:26
Still wish for this to be re-added or at least substituted with either an easy option or something with a bit better documentation.
But for those who wish to go back to when it was easy, use the last working version with:
`npx create-nuxt-app@2.15.0`

**Comment by eaguilarsaa** [comment] 2020-07-12 14:23
Thanks, using version 2.15.0 was helpful. I hope they re added it soon.

**Comment by manniL** [comment] 2020-07-12 15:40
Duplicate of #563

**Closed by manniL** 2020-07-12 15:40 UTC
