### ISSUE TITLE
nuxt version isn't the latest

### ISSUE THREAD

**Issue by mjbates7** [nuxt/create-nuxt-app#238] opened 2019-05-16 06:55 UTC
Hello,

When I use the create-nuxt-app command, 2.4.0 always gets installed.. Should this be set to be the latest 2.7.1? Or once we've used that command, do we then have to upgrade nuxt itself manually to the latest?

Any guidance appreciated 😃

**Comment by manniL** [comment] 2019-05-16 10:57
Duplicate of #209

**Closed by manniL** 2019-05-16 10:57 UTC
