### ISSUE TITLE
Version 2.11.0 is crashing

### ISSUE THREAD

**Issue by jeisonhiguita** [nuxt/create-nuxt-app#349] opened 2019-09-30 14:45 UTC
I'm running `npx create-nuxt-app <project-name>`

I got this:

```
create-nuxt-app v2.11.0
✨  Generating Nuxt.js project in renasci
Trace: { Error: Cannot find module './prompts'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/jhiguitasanchez/.config/yarn/global/node_modules/create-nuxt-app/saofile.js:9:12)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
    at sao.run.catch (/Users/jhiguitasanchez/.config/yarn/global/node_modules/create-nuxt-app/cli.js:46:17)
```

Node version: v10.16.0
npm version: 6.9.0

https://github.com/nuxt/create-nuxt-app/releases/tag/v2.11.0

**Comment by jeisonhiguita** [comment] 2019-09-30 14:46
version https://github.com/nuxt/create-nuxt-app/releases/tag/v2.10.1 is working very well

**Comment by wrtisans** [comment] 2019-09-30 15:02
How can i use old version to create nuxt-app?

**Comment by wmartins** [comment] 2019-09-30 15:15
@wrtisans I don't know how to specify a version with `yarn`. However, if you can use `npx`, try doing:

```bash
npx create-nuxt-app@2.10.1 warrenbrasil.com
```

**Comment by wrtisans** [comment] 2019-09-30 15:16
@wmartins thanks, it works!! hope can fix the bug soon!

**Comment by aldarund** [comment] 2019-09-30 19:39
duplicate of https://github.com/nuxt/create-nuxt-app/issues/350#issuecomment-536716487

**Closed by aldarund** 2019-09-30 19:39 UTC
