### ISSUE TITLE
Cannot destructure property 'nuxt' of 'this' as it is undefined

### ISSUE THREAD

**Issue by sandervspl** [nuxt/create-nuxt-app#1026] opened 2023-02-13 20:23 UTC
### Version
create-nuxt-app: v5.0.0

### Steps to reproduce

```
create-nuxt-app v5.0.0
✨  Generating Nuxt.js project in my-nuxt-app
? Project name: my-nuxt-app
? Programming language: TypeScript
? Package manager: Npm
? UI framework: Tailwind CSS
? Template engine: HTML
? Nuxt.js modules: Axios - Promise based HTTP client
? Linting tools: ESLint, Prettier
? Testing framework: None
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Server (Node.js hosting)
? Development tools: (Press <space> to select, <a> to toggle all, <i> to invert selection)
? Continuous integration: GitHub Actions (GitHub only)
? What is your GitHub username? sandervspl
? Version control system: Git
```

then

- cd my-nuxt-app
- npm run dev

### What is Expected?

No errors when starting dev server

### What is actually happening?

These warnings and errors show

```
WARN  webpack@5.75.0 is installed but ^4.46.0 is expected                                                                                                                                                  21:13:37

ℹ Using default Tailwind CSS file from runtime/tailwind.css                                                                                                                                nuxt:tailwindcss 21:13:38

 FATAL  Cannot destructure property 'nuxt' of 'this' as it is undefined.                                                                                                                                    21:13:38

  at postcss8Module (node_modules/@nuxt/postcss8/dist/index.js:15:10)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:435:21)
  at async setup (node_modules/@nuxtjs/tailwindcss/dist/module.mjs:186:7)
  at async ModuleContainer.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:167:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:34:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:342:5)
```

**Comment by manniL** [comment] 2023-02-16 18:00
Duplicate of https://github.com/nuxt/nuxt/issues/15507

**Closed by manniL** 2023-02-16 18:00 UTC
Labels: bug
